server:
  port: 8083

spring:
  application:
    name: eventrio-organization-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/EventrioOfficial}

eventrio:
  user-service:
    base-url: ${USER_SERVICE_URL:http://localhost:8082}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:}
    api-key: ${CLOUDINARY_API_KEY:}
    api-secret: ${CLOUDINARY_API_SECRET:}

management:
  health:
    mongo:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
