package com.eventrio.orchestrator.service;

import com.eventrio.common.enums.SagaStepStatusEnum;
import com.eventrio.common.enums.SagaWorkflowStatusEnum;
import com.eventrio.orchestrator.model.Project;
import com.eventrio.orchestrator.model.SagaWorkflow;
import com.eventrio.orchestrator.repository.ProjectRepository;
import com.eventrio.orchestrator.repository.SagaWorkflowRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Slf4j
@Service
@RequiredArgsConstructor
public class SagaEngine {

    private final SagaWorkflowRepository workflowRepository;
    private final ProjectRepository projectRepository;
    private final SagaRedisCacheService cacheService;
    private final SagaChannelPublisher channelPublisher;

    @Value("${eventrio.app-status:Production}")
    private String appStatus;

    public String startEngine(String userId, String prompt, String orgId, String pageId) {
        SagaWorkflow workflow = SagaWorkflow.builder()
                .userID(userId)
                .status(SagaWorkflowStatusEnum.PROCESSING)
                .createdTimestamp(Instant.now())
                .build();
        workflow = workflowRepository.save(workflow);

        if (pageId != null && !pageId.isBlank()) {
            cacheService.savePageId(userId, workflow.getId(), pageId);
        }

        executeWorkflow(userId, prompt, orgId, workflow.getId());
        return workflow.getId();
    }

    @Async("sagaTaskExecutor")
    public void executeWorkflow(String userId, String prompt, String orgId, String workflowId) {
        long start = System.currentTimeMillis();
        try {
            log.info("Executing workflow {} for user {}", workflowId, userId);

            Project project = projectRepository.save(createMinimalProject(userId, prompt, orgId));
            final String eventId = project.getId();

            workflowRepository.findById(workflowId).ifPresent(wf -> {
                wf.setEventID(eventId);
                workflowRepository.save(wf);
            });

            Instant startTime = Instant.now().plus(7, ChronoUnit.DAYS);
            Instant endTime = startTime.plus(2, ChronoUnit.HOURS);

            project.setStartDate(startTime);
            project.setEndDate(endTime);
            project.setEventPlan("Mock event plan generated from prompt: " + truncate(prompt, 200));
            project.setFb_post("Join us for " + project.getName() + "! Generated by Eventrio AI.");
            project.setMediaLinks(List.of("https://via.placeholder.com/1024x1024.png?text=Eventrio+Event"));
            project.setTargetingPointsToDiscuss(List.of("Welcome", "Keynote", "Networking"));
            projectRepository.save(project);

            Map<String, Object> cacheUpdates = new HashMap<>();
            cacheUpdates.put("userID", userId);
            cacheUpdates.put("workflowID", workflowId);
            cacheUpdates.put("projectID", project.getId());
            cacheUpdates.put("plan_des", project.getEventPlan());
            cacheUpdates.put("event_name", project.getName());
            cacheUpdates.put("start_time", startTime.toString());
            cacheUpdates.put("end_time", endTime.toString());
            cacheUpdates.put("event_description", project.getDescription());
            cacheService.mergeExecuteWorkflowCache(userId, workflowId, cacheUpdates);

            Map<String, Object> extra = new HashMap<>();
            extra.put("plan_des", project.getEventPlan());
            extra.put("event_name", project.getName());
            extra.put("start_time", startTime.toString());
            extra.put("end_time", endTime.toString());
            extra.put("event_description", project.getDescription());

            channelPublisher.publishStepCompletion(
                    "execute_workflow",
                    SagaStepStatusEnum.COMPLETED,
                    System.currentTimeMillis() - start,
                    userId,
                    workflowId,
                    project.getId(),
                    extra
            );
        } catch (Exception ex) {
            log.error("execute_workflow failed for workflow {}: {}", workflowId, ex.getMessage(), ex);
            channelPublisher.publishStepCompletion(
                    "execute_workflow",
                    SagaStepStatusEnum.FAILED,
                    System.currentTimeMillis() - start,
                    userId,
                    workflowId,
                    null,
                    Map.of("error", ex.getMessage())
            );
        }
    }

    public void markWorkflowCompleted(String workflowId) {
        workflowRepository.findById(workflowId).ifPresent(wf -> {
            wf.setStatus(SagaWorkflowStatusEnum.COMPLETED);
            wf.setEndingTimestamp(Instant.now());
            workflowRepository.save(wf);
        });
    }

    private Project createMinimalProject(String userId, String prompt, String orgId) {
        String eventName = deriveEventName(prompt);
        return Project.builder()
                .name(eventName)
                .description(truncate(prompt, 500))
                .ownerID(userId)
                .orgID(orgId)
                .attendeeCountExpected(100)
                .industry(List.of("Technology"))
                .userRole(List.of("manager"))
                .isEventStarted(false)
                .build();
    }

    private String deriveEventName(String prompt) {
        if (prompt == null || prompt.isBlank()) {
            return "AI Generated Event";
        }
        String trimmed = prompt.trim();
        if (trimmed.length() <= 60) {
            return trimmed;
        }
        return trimmed.substring(0, 57) + "...";
    }

    private String truncate(String value, int max) {
        if (value == null) {
            return "";
        }
        return value.length() <= max ? value : value.substring(0, max);
    }
}
